package com.my.pojo;

public class GoodsList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_list.list_id
     *
     * @mbggenerated
     */
    private Integer listId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_list.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_list.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_list.goods_num
     *
     * @mbggenerated
     */
    private Integer goodsNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_list.list_id
     *
     * @return the value of goods_list.list_id
     *
     * @mbggenerated
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_list.list_id
     *
     * @param listId the value for goods_list.list_id
     *
     * @mbggenerated
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_list.order_id
     *
     * @return the value of goods_list.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_list.order_id
     *
     * @param orderId the value for goods_list.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_list.goods_id
     *
     * @return the value of goods_list.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_list.goods_id
     *
     * @param goodsId the value for goods_list.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_list.goods_num
     *
     * @return the value of goods_list.goods_num
     *
     * @mbggenerated
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_list.goods_num
     *
     * @param goodsNum the value for goods_list.goods_num
     *
     * @mbggenerated
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }
}