package com.my.pojo;

public class VipCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipcard.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipcard.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipcard.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipcard.card_id
     *
     * @return the value of vipcard.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipcard.card_id
     *
     * @param cardId the value for vipcard.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipcard.user_id
     *
     * @return the value of vipcard.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipcard.user_id
     *
     * @param userId the value for vipcard.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipcard.money
     *
     * @return the value of vipcard.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipcard.money
     *
     * @param money the value for vipcard.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}