package com.my.dao;

import com.my.pojo.GoodsList;
import com.my.pojo.GoodsListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int countByExample(GoodsListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int deleteByExample(GoodsListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int insert(GoodsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int insertSelective(GoodsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    List<GoodsList> selectByExample(GoodsListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    GoodsList selectByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodsList record, @Param("example") GoodsListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodsList record, @Param("example") GoodsListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsList record);
}