package com.my.dao;

import com.my.pojo.VipCard;
import com.my.pojo.VipCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int countByExample(VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int deleteByExample(VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int insert(VipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int insertSelective(VipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    List<VipCard> selectByExample(VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    VipCard selectByPrimaryKey(String cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipCard record, @Param("example") VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipCard record, @Param("example") VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipcard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipCard record);
}